import { Component } from '@angular/core';
@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss'],
})
export class AppComponent {
  public appPages = [
    { title: 'Material Theme Home Page 1', url: '/m-home-page1', icon: 'heart' },
    { title: 'Material Theme Home Page 2', url: '/mhome2', icon: 'heart' },
    { title: 'Fruit App Details Page', url: '/detail', icon: 'heart' },
    { title: 'Fruit App Product List Page 1', url: '/my-orders', icon: 'heart' },
    { title: 'Fruit App Product List Page 2', url: '/favourites', icon: 'heart' },
    { title: 'Fruit App Add Product Page ', url: '/shopping-cart', icon: 'heart' },
    { title: 'Fruit App Add Card Page ', url: '/payment-card', icon: 'heart' },
    { title: 'Fruit App Market Page ', url: '/fruit-market', icon: 'heart' },
    { title: 'Fruit App Notificatiom Setting ', url: '/notification-settings', icon: 'heart' },
    { title: 'Fruit App Verification Code Successful ', url: '/verification-code', icon: 'heart' },
    { title: 'Fruit App Verification Code Page ', url: '/code-verification', icon: 'heart' },
    { title: 'Fruit App Notification Page ', url: '/notification-page', icon: 'heart' },
    { title: 'Fruit App Account Setting Page ', url: '/account-setting', icon: 'heart' },
    { title: 'Fruit App Menu Page ', url: '/menu-page', icon: 'heart' },
    { title: 'Home 1', url: '/home1', icon: 'heart' },
    { title: 'Home 2', url: '/home2', icon: 'heart' },
    { title: 'Home 3', url: '/home3', icon: 'heart' },
    { title: 'Home 4', url: '/home4', icon: 'heart' },
    { title: 'Home 5', url: '/home5', icon: 'heart' },
    { title: 'Home 6', url: '/home6', icon: 'heart' },
    { title: 'Next page 1', url: '/next1', icon: 'heart' },
    { title: 'Next page 2', url: '/next2', icon: 'heart' },
    { title: 'Next page 3', url: '/next3', icon: 'heart' },
    { title: 'Next page 4', url: '/next4', icon: 'heart' },
    { title: 'Next page 5', url: '/next5', icon: 'heart' },
    { title: 'Next page 6', url: '/next6', icon: 'heart' },
    { title: 'Subject 1', url: '/subject1', icon: 'heart' },
    { title: 'Subject 2', url: '/subject2', icon: 'heart' },
    { title: 'Subject 3', url: '/subject3', icon: 'heart' },
    { title: 'Subject 4', url: '/subject4', icon: 'heart' },
    { title: 'Subject 5', url: '/subject5', icon: 'heart' },
    { title: 'Subject 6', url: '/subject6', icon: 'heart' },
    { title: 'List 1', url: '/list1', icon: 'heart' },
    { title: 'List 2', url: '/list2', icon: 'heart' },
    { title: 'List 3', url: '/list3', icon: 'heart' },
    { title: 'List 4', url: '/list4', icon: 'heart' },
    { title: 'List 5', url: '/list5', icon: 'heart' },
    { title: 'List 6', url: '/list6', icon: 'heart' },
    { title: 'Payement 1', url: '/payment1', icon: 'heart' },
    { title: 'Payement 2', url: '/payment2', icon: 'heart' },
    { title: 'Payement 3', url: '/payment3', icon: 'heart' },
    { title: 'Payement 4', url: '/payment4', icon: 'heart' },
    { title: 'Payement 5', url: '/payment5', icon: 'heart' },
    { title: 'Payement 6', url: '/payment6', icon: 'heart' },
    { title: 'Profile 1', url: '/profile1', icon: 'heart' },
    { title: 'Profile 2', url: '/profile2', icon: 'heart' },
    { title: 'Profile 3', url: '/profile3', icon: 'heart' },
    { title: 'Profile 4', url: '/profile4', icon: 'heart' },
    { title: 'Profile 5', url: '/profile5', icon: 'heart' },
    { title: 'Profile 6', url: '/profile6', icon: 'heart' },
    { title: 'Profile 7', url: '/demo3', icon: 'heart' },
    { title: 'Login Page', url: '/login', icon: 'heart' },
    { title: 'Home Page', url: '/home', icon: 'heart' },
    { title: 'Verify Number', url: '/verify-number', icon: 'heart' },

  ];

  constructor() { }
}
